version: '3.9'

services:
  mysql:
    image: mysql:8.4

    container_name: ${PROJECT_NAME}_mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "${MYSQL_PORT}:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    container_name: ${PROJECT_NAME}_phpmyadmin

    restart: unless-stopped

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "${PHPMYADMIN_PORT}:80"

    depends_on:
      - mysql

    networks:
      - internal

volumes:
  mysql_data:

networks:
  internal:
